<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Janodya-lap" failures="1" tests="6" name="optiomaxWebTestCases.SignInTest" time="82.952" errors="0" timestamp="2024-05-21T11:07:51 IST" skipped="0">
  <testcase classname="optiomaxWebTestCases.SignInTest" name="testInvalidSignInWithIncorrectEmail" time="12.977"/>
  <system-out/>
  <testcase classname="optiomaxWebTestCases.SignInTest" name="testInvalidSignInWithIncorrectPassword" time="18.801"/>
  <system-out/>
  <testcase classname="optiomaxWebTestCases.SignInTest" name="testInvalidSignInWithEmptyEmail" time="12.851"/>
  <system-out/>
  <testcase classname="optiomaxWebTestCases.SignInTest" name="testInvalidSignInWithEmptyPassword" time="12.772"/>
  <system-out/>
  <testcase classname="optiomaxWebTestCases.SignInTest" name="testInvalidSignInWithInvalidEmail" time="12.779"/>
  <system-out/>
  <testcase classname="optiomaxWebTestCases.SignInTest" name="testValidSignIn" time="12.772">
    <failure message="Sign-in should be successful with correct email and password. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Sign-in should be successful with correct email and password. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at optiomaxWebTestCases.SignInTest.testValidSignIn(SignInTest.java:120)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testValidSignIn -->
  <system-out/>
</testsuite> <!-- optiomaxWebTestCases.SignInTest -->
